// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dtc.Infrastructure.Pesistence.SQLServer;

#nullable disable

namespace dtc.Infrastructure.Persistence.SQLServer.Migrations
{
    [DbContext(typeof(SQLDBContext))]
    [Migration("20260425095615_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dtc.Domain.Entities.Classes.Attendance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClassScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("ClassScheduleId", "StudentId")
                        .IsUnique();

                    b.ToTable("Attendance", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc9"),
                            CheckedAt = new DateTime(2026, 3, 15, 1, 5, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            IsPresent = true,
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccca"),
                            CheckedAt = new DateTime(2026, 4, 20, 1, 35, 0, 0, DateTimeKind.Utc),
                            ClassScheduleId = new Guid("77777777-7777-7777-7777-777777777772"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 45, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            IsPresent = false,
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStudents")
                        .HasColumnType("int");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("TermId");

                    b.ToTable("Classes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            ClassName = "B2-01-Q1",
                            ClassType = "Theory",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CurrentStudents = 1,
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            MaxStudents = 25,
                            Status = "InProgress",
                            TermId = new Guid("55555555-5555-5555-5555-555555555551"),
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666662"),
                            ClassName = "C-01-TD",
                            ClassType = "Practice",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 35, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CurrentStudents = 1,
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            MaxStudents = 20,
                            Status = "Pending",
                            TermId = new Guid("55555555-5555-5555-5555-555555555552"),
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.ClassSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("InstructorId");

                    b.ToTable("ClassSchedules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            AddressId = 1,
                            ClassId = new Guid("66666666-6666-6666-6666-666666666661"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndTime = new DateTime(2026, 3, 15, 3, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            StartTime = new DateTime(2026, 3, 15, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777772"),
                            AddressId = 2,
                            ClassId = new Guid("66666666-6666-6666-6666-666666666662"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 40, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            EndTime = new DateTime(2026, 4, 20, 3, 30, 0, 0, DateTimeKind.Utc),
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            StartTime = new DateTime(2026, 4, 20, 1, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.ClassStudent", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ClassId", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("ClassStudents", (string)null);

                    b.HasData(
                        new
                        {
                            ClassId = new Guid("66666666-6666-6666-6666-666666666661"),
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            ClassId = new Guid("66666666-6666-6666-6666-666666666662"),
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.InstructorLeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LeaveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("InstructorLeaveRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc5"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            LeaveDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Nghi phep ca nhan.",
                            Status = "Approved",
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc6"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 50, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            LeaveDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Reason = "Tham gia boi duong nghiep vu.",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.StudentDrivingDistance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("EveningDistanceKm")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("MaxEveningDistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("MaxMorningDistanceKm")
                        .HasColumnType("float");

                    b.Property<double>("MorningDistanceKm")
                        .HasColumnType("float");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentDrivingDistances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc3"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            EveningDistanceKm = 18.199999999999999,
                            IsDeleted = false,
                            MaxEveningDistanceKm = 40.0,
                            MaxMorningDistanceKm = 80.0,
                            MorningDistanceKm = 42.5,
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc4"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 55, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            EveningDistanceKm = 6.0,
                            IsDeleted = false,
                            MaxEveningDistanceKm = 30.0,
                            MaxMorningDistanceKm = 60.0,
                            MorningDistanceKm = 12.0,
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Collaborators.CollaboratorCommission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReferralRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CollaboratorId");

                    b.HasIndex("ReferralRegistrationId");

                    b.ToTable("CollaboratorCommissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb5"),
                            Amount = 800000m,
                            CollaboratorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb6"),
                            Amount = 1250000m,
                            CollaboratorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            PaidAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Paid"
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Collaborators.ReferralCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CollaboratorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CollaboratorId");

                    b.ToTable("ReferralCodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            Code = "CTVQ1A01",
                            CollaboratorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            UsedCount = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            Code = "CTVTDA02",
                            CollaboratorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 1, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            IsDeleted = false,
                            UsedCount = 0
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Collaborators.ReferralRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseRegistrationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferralCodeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseRegistrationId");

                    b.HasIndex("ReferralCodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("ReferralRegistrations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3"),
                            ReferralCodeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1"),
                            RegisteredAt = new DateTime(2026, 2, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb4"),
                            ReferralCodeId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2"),
                            RegisteredAt = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PassScore")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("ExamBatchId");

                    b.ToTable("Exams", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999991"),
                            AddressId = 1,
                            CourseId = new Guid("44444444-4444-4444-4444-444444444441"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            DurationMinutes = 25,
                            ExamBatchId = new Guid("88888888-8888-8888-8888-888888888881"),
                            ExamDate = new DateTime(2026, 5, 5, 1, 0, 0, 0, DateTimeKind.Utc),
                            ExamName = "Thi Ly Thuyet B2",
                            ExamType = "Theory",
                            IsDeleted = false,
                            PassScore = 32,
                            Status = "Scheduled",
                            TotalScore = 35,
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999992"),
                            AddressId = 2,
                            CourseId = new Guid("44444444-4444-4444-4444-444444444442"),
                            CreatedAt = new DateTime(2026, 1, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            DurationMinutes = 40,
                            ExamBatchId = new Guid("88888888-8888-8888-8888-888888888882"),
                            ExamDate = new DateTime(2026, 6, 8, 2, 0, 0, 0, DateTimeKind.Utc),
                            ExamName = "Thi Thuc Hanh C",
                            ExamType = "Practice",
                            IsDeleted = false,
                            PassScore = 80,
                            Status = "Draft",
                            TotalScore = 100
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.ExamBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BatchName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentCandidates")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExamStartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxCandidates")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegistrationEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RegistrationStartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("ExamBatches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            BatchName = "Ky thi sat hach thang 05",
                            CenterId = new Guid("33333333-3333-3333-3333-333333333331"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CurrentCandidates = 1,
                            ExamStartDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MaxCandidates = 100,
                            RegistrationEndDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            RegistrationStartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScopeType = "Center",
                            Status = "OpenForRegistration",
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888882"),
                            BatchName = "Ky thi sat hach thang 06",
                            CreatedAt = new DateTime(2026, 1, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CurrentCandidates = 1,
                            ExamStartDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsDeleted = false,
                            MaxCandidates = 80,
                            RegistrationEndDate = new DateTime(2026, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            RegistrationStartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ScopeType = "National",
                            Status = "Pending"
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.ExamRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ExamBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExamBatchId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamRegistrations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            ExamBatchId = new Guid("88888888-8888-8888-8888-888888888881"),
                            IsDeleted = false,
                            IsPaid = true,
                            RegistrationDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2"),
                            CreatedAt = new DateTime(2026, 1, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            ExamBatchId = new Guid("88888888-8888-8888-8888-888888888882"),
                            IsDeleted = false,
                            IsPaid = false,
                            RegistrationDate = new DateTime(2026, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.ExamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<double>("Score")
                        .HasColumnType("float");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("ExamResults", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3"),
                            AttemptNo = 1,
                            ExamId = new Guid("99999999-9999-9999-9999-999999999991"),
                            IsPassed = true,
                            Score = 33.0,
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4"),
                            AttemptNo = 1,
                            ExamId = new Guid("99999999-9999-9999-9999-999999999992"),
                            IsPassed = false,
                            Score = 78.0,
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.SampleExamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SampleExamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("TotalScore")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserAnswersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SampleExamResult");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd3"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("22222222-2222-2222-2222-222222222222"),
                            DurationSeconds = 1320,
                            IsDeleted = false,
                            IsPassed = true,
                            SampleExamId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee5"),
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TotalScore = 34.0,
                            UserAnswersJson = "{\"1\":\"A\",\"2\":\"C\"}"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd4"),
                            CreatedAt = new DateTime(2026, 1, 10, 15, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            DurationSeconds = 1600,
                            IsDeleted = false,
                            IsPassed = false,
                            SampleExamId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeee6"),
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TotalScore = 24.0,
                            UserAnswersJson = "{\"1\":\"B\",\"2\":\"D\"}"
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Location.Center", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxStudentPerClass")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfClasses")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Centers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            Address = "12 Nguyen Hue, Quan 1",
                            CenterName = "Trung Tam Lai Xe Quan 1",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "q1-center@dtc.local",
                            IsActive = true,
                            IsDeleted = false,
                            MaxStudentPerClass = 25,
                            NumberOfClasses = 6,
                            Phone = "+842812345678",
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333332"),
                            Address = "99 Vo Van Ngan, Thu Duc",
                            CenterName = "Trung Tam Lai Xe Thu Duc",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 5, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "thuduc-center@dtc.local",
                            IsActive = true,
                            IsDeleted = false,
                            MaxStudentPerClass = 30,
                            NumberOfClasses = 8,
                            Phone = "+842876543210",
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Permissions.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderPublicId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Documents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc1"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Extension = ".pdf",
                            FileName = "cccd-student-demo.pdf",
                            IsDeleted = false,
                            IsVerified = true,
                            ProviderPublicId = "user_docs/student-demo-cccd",
                            ResourceType = "raw",
                            Size = 512000,
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Version = "1710000001"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc2"),
                            CreatedAt = new DateTime(2026, 1, 10, 13, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Extension = ".jpg",
                            FileName = "giay-phep-instructor-demo.jpg",
                            IsDeleted = false,
                            IsVerified = false,
                            ProviderPublicId = "user_docs/instructor-demo-license",
                            ResourceType = "image",
                            Size = 348000,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Version = "1710000002"
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Permissions.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            RoleName = "Instructor"
                        },
                        new
                        {
                            Id = 6,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Permissions.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ClerkId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClerkId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AvatarUrl = "https://cdn.example.com/avatar/instructor-demo.png",
                            ClerkId = "clerk_instructor_demo",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "instructor.demo@dtc.local",
                            FullName = "Tran Van Huong",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginAt = new DateTime(2026, 1, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "+84901111222",
                            RoleId = 3,
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AvatarUrl = "https://cdn.example.com/avatar/student-demo.png",
                            ClerkId = "clerk_student_demo",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 10, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Email = "student.demo@dtc.local",
                            FullName = "Le Thi Minh",
                            IsActive = true,
                            IsDeleted = false,
                            LastLoginAt = new DateTime(2026, 1, 16, 9, 0, 0, 0, DateTimeKind.Utc),
                            Phone = "+84903333444",
                            RoleId = 6,
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Permissions.UserCenter", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "CenterId");

                    b.HasIndex("CenterId");

                    b.ToTable("UserCenters", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CenterId = new Guid("33333333-3333-3333-3333-333333333331")
                        },
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            CenterId = new Guid("33333333-3333-3333-3333-333333333332")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Terms.CourseRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedTermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("OriginalFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTermId");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("CourseRegistrations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd1"),
                            AssignedTermId = new Guid("55555555-5555-5555-5555-555555555551"),
                            CourseId = new Guid("44444444-4444-4444-4444-444444444441"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Notes = "Da xac nhan hoc phi dot 1.",
                            OriginalFee = 12500000m,
                            RegistrationDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Approved",
                            TotalFee = 12500000m,
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            UserId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-ddddddddddd2"),
                            CourseId = new Guid("44444444-4444-4444-4444-444444444442"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 30, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Notes = "Cho xep lop.",
                            OriginalFee = 15800000m,
                            RegistrationDate = new DateTime(2026, 2, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Pending",
                            TotalFee = 15800000m,
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Terms.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentStudents")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TermName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Terms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            CourseId = new Guid("44444444-4444-4444-4444-444444444441"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CurrentStudents = 1,
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MaxStudents = 25,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            TermName = "Dot 03-2026 B2",
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555552"),
                            CourseId = new Guid("44444444-4444-4444-4444-444444444442"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 25, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            CurrentStudents = 1,
                            EndDate = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsDeleted = false,
                            MaxStudents = 20,
                            StartDate = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            TermName = "Dot 04-2026 C",
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Training.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInWeeks")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LicenseType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaxStudents")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CenterId");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            CenterId = new Guid("33333333-3333-3333-3333-333333333331"),
                            CourseName = "Khoa B2 Tieu Chuan",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Khoa hoc B2 danh cho hoc vien moi.",
                            DurationInWeeks = 12,
                            IsActive = true,
                            IsDeleted = false,
                            LicenseType = "B",
                            MaxStudents = 25,
                            Price = 12500000m,
                            ThumbnailUrl = "https://cdn.example.com/course/b2.jpg",
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444442"),
                            CenterId = new Guid("33333333-3333-3333-3333-333333333332"),
                            CourseName = "Khoa C Nang Cao",
                            CreatedAt = new DateTime(2026, 1, 10, 8, 20, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Khoa hoc C danh cho tai xe tai nhe.",
                            DurationInWeeks = 16,
                            IsActive = true,
                            IsDeleted = false,
                            LicenseType = "C",
                            MaxStudents = 20,
                            Price = 15800000m,
                            ThumbnailUrl = "https://cdn.example.com/course/c.jpg",
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Training.StudentEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PunctualityScore")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("StudentEvaluation");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc7"),
                            ClassId = new Guid("66666666-6666-6666-6666-666666666661"),
                            CreatedAt = new DateTime(2026, 1, 10, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            EvaluationDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Note = "Hoc vien tien bo tot trong sa hinh.",
                            PunctualityScore = 9,
                            SkillLevel = 8,
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2026, 1, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedBy = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-ccccccccccc8"),
                            ClassId = new Guid("66666666-6666-6666-6666-666666666662"),
                            CreatedAt = new DateTime(2026, 1, 10, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            EvaluationDate = new DateTime(2026, 4, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsDeleted = false,
                            Note = "Can tang so buoi luyen tap ngoai duong truong.",
                            PunctualityScore = 7,
                            SkillLevel = 6,
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.Attendance", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Classes.ClassSchedule", null)
                        .WithMany()
                        .HasForeignKey("ClassScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.Class", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Terms.Term", null)
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.ClassSchedule", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Classes.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.ClassStudent", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Classes.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.InstructorLeaveRequest", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Classes.StudentDrivingDistance", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Collaborators.CollaboratorCommission", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Collaborators.ReferralRegistration", null)
                        .WithMany()
                        .HasForeignKey("ReferralRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("dtc.Domain.Entities.Collaborators.ReferralCode", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("CollaboratorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Collaborators.ReferralRegistration", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Terms.CourseRegistration", null)
                        .WithMany()
                        .HasForeignKey("CourseRegistrationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("dtc.Domain.Entities.Collaborators.ReferralCode", null)
                        .WithMany()
                        .HasForeignKey("ReferralCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.Exam", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Training.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Exams.ExamBatch", null)
                        .WithMany()
                        .HasForeignKey("ExamBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.ExamBatch", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Location.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Center");
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.ExamRegistration", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Exams.ExamBatch", null)
                        .WithMany()
                        .HasForeignKey("ExamBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Exams.ExamResult", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Permissions.Document", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Permissions.UserCenter", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Location.Center", null)
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Terms.CourseRegistration", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Terms.Term", null)
                        .WithMany()
                        .HasForeignKey("AssignedTermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("dtc.Domain.Entities.Training.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("dtc.Domain.Entities.Permissions.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Terms.Term", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Training.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("dtc.Domain.Entities.Training.Course", b =>
                {
                    b.HasOne("dtc.Domain.Entities.Location.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });
#pragma warning restore 612, 618
        }
    }
}
