name: Master Driving CI-CD

on:
  push:
    branches:
      - main
      - develop # Cho phép chạy CI để kiểm tra lỗi code trên develop
  workflow_dispatch:

jobs:
  # JOB 1: CHỈ BUILD VÀ TEST (Nhánh nào cũng chạy)
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Build & Test
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test --no-build
      - name: Publish Artifact
        run: dotnet publish -c Release -o ./publish
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  # JOB 2: CHỈ DEPLOY (CẤM các nhánh khác ngoài main)
  deploy:
    runs-on: windows-latest
    needs: build
    # ĐIỀU KIỆN SỐNG CÒN: Chỉ chạy nếu là nhánh main
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5ECD167A916E4770B7EC54C0FD492479 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0C811042532B4FF3BCC8DC5D5999E135 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22E14270941A4364B0E20BBA1D20D7A8 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'masterdrivingtrainingcenter'
          slot-name: 'Production'
          package: ./publish